### PR TITLE
Double Buffer Reading to Improve IO Performance on Marker Reading

### PR DESCRIPTION
**Pull request by aabiddanda**
I finished my changes for IO in the readMarkers function using two character buffers rather than just reading character by character. From my tests increasing the size of the buffer beyond 2048 bytes does not really improve the performance considerably. This may change for larger file sizes though. 

In comparison to the previous method for reading in markers this reduces the time to read around 500k markers by 80%. 

Other smaller additions include a "make install" command which links the library to /usr/local/lib as well as linking the header files to /usr/local/include/.

### CODE REVIEW

**Comment by aabiddanda** [comment]
Here is a diff with the whitespace removed : https://github.com/amythewilliams/genetio/pull/1/files?w=1

Definitely shows the changes made in marker.cc better.

**Comment by aabiddanda** [comment]
Previous commits included an error where the marker name itself was not read properly. This has been resolved now.

**Comment by williamslab** [comment]
This is quite nice. A few comments/change requests below. Let me know your thoughts:
1. Since there's no testing directory in the repository, I'm tempted not to include the change to .gitignore
2. I'm not sure I like the `make clean` deleting files installed to system directories. The user may not have permission (at least currently) to modify those files. Tempted to say `make clean` should only affect local repository. Could add `make uninstall` to do the other?
3. The missing '@' from my email in marker.cc is intentional: hoping to avoid spammers that.
4. I prefer helper functions such as "skipWhitespace" and "readDoubleBuffer" to be private methods of the class rather than functions.
5. TODO on marker.cc line 302-303 looks like it could be removed?
6. Can change this:
   tmpStr.assign(tmpStrX); mapPos = atof(tmpStr.c_str());
   to
   mapPos = atof(tmpStr);
   and remove the tmpStr variable. This applies a few places. Can just assign alleles[0] directly from tmpStrX[0], too.
7. Given the above could change name of tmpStrX to tmpStr.
8. On non-SNP variants: for now I think the error is fine. I need to think about how to store alleles and the current code requires single letters. Thus the error.
9. Stylistic thing: I prefer no space between either \* and & and variable name as occurs in readDoubleBuffer() method.
10. I think we discussed how to include the phenotype? (Re: your TODO)

Two other things:
- Question: what happens if there are trailing spaces on a line before the the '\n'?
- Ideally, we'd get rid of the markerName.assign() and chromName.assign(), etc. statements and just use pointers into these buffers. Only worry is if a line is longer than the size of a buffer, but shouldn't happen in practice. Still you'd want to check for this and throw an error if some token points into a buffer you're about to clobber. Make sense? What do you think?

Otherwise seems good! Would be happy to pull with these changes.

**Comment by aabiddanda** [comment]
All the required changes should be in the most recent commit to master. One thing that I have not done is change the phenotype coding to handle quantitative data. That would result in changes in a lot of the source files for the representation of the samples in particular. That seemed a little out of scope of this particular pull request. All the other concerns should be addressed. Here is a more recent diff of the branches while not counting whitespace : https://github.com/amythewilliams/genetio/pull/1/files?w=1

**Pull request merged**
